<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="1.0" />

    <material name="grey">
        <color rgba="0.7 0.7 0.7 1.0"/>
    </material>
    <material name="blue">
        <color rgba="0.0 0.5 1.0 1.0"/>
    </material>
    <material name="green">
        <color rgba="0.0 0.6 0.0 1.0"/>
    </material>
    <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
    </material>

    <link name="base_footprint">
    </link>

    <link name ="base_link">
        <visual>
            <geometry>
                <box size="${base_length} 0.4 0.2"/>
            </geometry>
            <origin xyz="0.0 0.0 0.1" rpy="0.0 0.0 0.0"/>
            <material name="green"/>
        </visual>
    </link>
    
    <link name="lidar">
        <visual>
            <geometry>
                <cylinder radius="0.1" length="0.05"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <material name="blue"/>
        </visual>
    </link>

    <link name="left_wheel">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="${pi / 2} 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.1" length="0.05"/>
            </geometry>
            <material name="grey"/>
        </visual>
    </link>

    <link name="right_wheel">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="${pi / 2.0} 0.0 0.0"/>
            <geometry>
                <cylinder radius="0.1" length="0.05"/>
            </geometry>
            <material name="grey"/>
        </visual>
    </link>

    <link name="caster_wheel">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
            <material name="grey"/>
        </visual>
    </link>

    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar"/>
        <origin xyz="0.0 0.0 0.225" rpy="0.0 0.0 0.0"/>
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <origin xyz="${-base_length / 4.0} 0.225 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <axis xyz="0.0 1.0 0.0"/>
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <origin xyz="${-base_length / 4.0} -0.225 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <axis xyz="0.0 1.0 0.0"/>
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <origin xyz="${base_length / 3.0} 0.0 -0.05" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="caster_wheel"/>
    </joint>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 0.1" rpy="0.0 0.0 0.0"/>
    </joint>

</robot>